version: '3.8'
services:
  app:
    build: .
    ports:
      - '4200:4200'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ng serve --host 0.0.0.0
    environment:
      - PORT=4200
